version: '3.8'
services:
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=event
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart: always
  event-manager-backend:
    image: dragalone/event-manager-backend:latest
#    build:
#      context: ../
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  nginx-vue:
    image: dragalone/event-manager-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - event-manager-backend
      - postgres